### ISSUE TITLE
Fix lint error

### ISSUE THREAD

**Issue by bmwilly** [contiamo/contiamo-client-python#17]
There is a single lint error on #16:
```
➜  contiamo-client-python git:(update-contracts) flake8 contiamo
contiamo/resources.py:115:41: F821 undefined name 'response'
```
I'm not sure what the intended behavior here is.

**Comment by bmwilly** [comment]
This is causing our builds to fail: https://travis-ci.org/contiamo/contiamo-client-python/builds/354421209

**Comment by ian-contiamo** [comment]
Fixed (and made the intent clearer, hopefully).

**Comment by bmwilly** [comment]
Fixed by https://github.com/contiamo/contiamo-client-python/commit/0a8f0c1a41dcbd925bed8038504fa6f6fcc5b8f5
